version: '3.3'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Porta para comunicação AMQP
      - "15672:15672"     # Porta para o painel de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  pagamento-service:
    build:
      context: ./
    container_name: pagamento_service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
